a = [0, 1, 2, 'napis', ('x', 'y')]
print('lista:')
print(a)
print()
print('wyszukiwanie:')
print('0 in a =>', 0 in a)
print("'n' in a =>", 'n' in a)
print("'napis' in a =>", 'napis' in a)
print("('x',) in a =>", ('x',) in a)
print("('x','y') in a =>", ('x', 'y') in a)
